# Universal information
title: Coding it Forward
description: We're a rebel alliance of young people using technology for social good.

show_downloads: false

github:
    is_project_page: true
    repository_url: https://github.com/CodingItForward/codingitforward.github.io

external:
    medium: https://blog.codingitforward.com/
    mailing_list: https://groups.google.com/forum/#!forum/coding-it-forward
    facebook: https://www.facebook.com/groups/230953293978006/

# Bootswatch theme
bs_theme: readable

# other settings
